name: Deploy Timestamp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: timestamp.lat
          username: edvards
          key: ${{ secrets.DEPLOY_KEY }}
          port: 69
          script: |
            cd /var/www/timestamp
            git fetch origin main
            git reset --hard origin/main

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan queue:restart